################################################################################
#
# external-fw
#
################################################################################

MARVELL_EXTERNAL_FW_DEFS = $(call qstrip,$(BR2_MARVELL_EXTERNAL_FW_DEFS))

MARVELL_EXTERNAL_FW_PLATFORM = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_PLATFORM))

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_CUSTOM_GIT),y)
MARVELL_EXTERNAL_FW_SITE = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_CUSTOM_REPO_URL))
MARVELL_EXTERNAL_FW_SITE_METHOD = git
MARVELL_EXTERNAL_FW_VERSION = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_CUSTOM_REPO_VERSION))
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_CUSTOM_TARBALL),y)
MARVELL_EXTERNAL_FW_TARBALL = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_CUSTOM_TARBALL_LOCATION))
MARVELL_EXTERNAL_FW_SITE = $(patsubst %/,%,$(dir $(MARVELL_EXTERNAL_FW_TARBALL)))
MARVELL_EXTERNAL_FW_SITE_METHOD = file
MARVELL_EXTERNAL_FW_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_TARBALL))
MARVELL_EXTERNAL_FW_VERSION = $(call qstrip,$(BR2_MARVELL_RELEASE_ID))
endif

MARVELL_EXTERNAL_FW_DEPENDENCIES = host-python3 host-openjdk-bin python-cffi host-python-cryptography host-python-six host-python-pyelftools host-python-gpt-image python-pyyaml host-cmake host-python-pyyaml host-python-pycryptodomex host-python-pyyaml-include host-util-linux host-python-git


ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_ECP_HAL),y)
MARVELL_EXTERNAL_FW_DEPENDENCIES += host-python-west host-zephyr
MARVELL_EXTERNAL_FW_ECP_LOC = xcp/ecp/ecp_app

else

MARVELL_EXTERNAL_FW_ECP_LOC = ecp

endif


ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_CUSTOM_GIT),y)
define MARVELL_EXTERNAL_FW_EXTRACT_TOOLCHAIN_CMDS
	ln -sf $(BR2_TOOLCHAIN_EXTERNAL_PATH) $(@D)/tools
endef
ifeq ($(BR2_MARVELL_SOC_FAMILY),"CN20K")
define MARVELL_EXTERNAL_FW_EXTRACT_ADDITIONAL_TOOLCHAIN_CMDS
ln -sf $(BR2_ADDITIONAL_TOOLCHAIN_EXTERNAL_PATH) $(@D)/tools-armv7
endef
endif
else
MARVELL_EXTERNAL_FW_TOOLCHAIN_TARBALL = $(call qstrip,$(BR2_TOOLCHAIN_EXTERNAL_URL))
MARVELL_EXTERNAL_FW_TOOLCHAIN_SITE = $(subst file://,/,$(dir $(MARVELL_EXTERNAL_FW_TOOLCHAIN_TARBALL)))
MARVELL_EXTERNAL_FW_TOOLCHAIN_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_TOOLCHAIN_TARBALL))
MARVELL_EXTERNAL_FW_ADDITIONAL_TOOLCHAIN_TARBALL = $(call qstrip,$(BR2_ADDITIONAL_TOOLCHAIN_EXTERNAL_URL))
MARVELL_EXTERNAL_FW_ADDITIONAL_TOOLCHAIN_SITE = $(subst file://,/,$(dir $(MARVELL_EXTERNAL_FW_ADDITIONAL_TOOLCHAIN_TARBALL)))
MARVELL_EXTERNAL_FW_ADDITIONAL_TOOLCHAIN_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_ADDITIONAL_TOOLCHAIN_TARBALL))
define MARVELL_EXTERNAL_FW_EXTRACT_TOOLCHAIN_CMDS
	mkdir $(@D)/tools
	tar xf  $(MARVELL_EXTERNAL_FW_TOOLCHAIN_SITE)$(MARVELL_EXTERNAL_FW_TOOLCHAIN_SOURCE) --strip-components=1 -C $(@D)/tools
endef
ifeq ($(BR2_MARVELL_SOC_FAMILY),"CN20K")
define MARVELL_EXTERNAL_FW_EXTRACT_ADDITIONAL_TOOLCHAIN_CMDS
	mkdir $(@D)/tools-armv7
	tar xf  $(MARVELL_EXTERNAL_FW_ADDITIONAL_TOOLCHAIN_SITE)$(MARVELL_EXTERNAL_FW_ADDITIONAL_TOOLCHAIN_SOURCE) --strip-components=1 -C $(@D)/tools-armv7
endef
endif
endif

# ATF #
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_ATF_CUSTOM_GIT),y)
MARVELL_EXTERNAL_FW_ATF_SITE = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_ATF_CUSTOM_REPO_URL))
MARVELL_EXTERNAL_FW_ATF_SITE_METHOD = git
MARVELL_EXTERNAL_FW_ATF_VERSION = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_ATF_CUSTOM_REPO_VERSION))
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_ATF_CUSTOM_TARBALL),y)
MARVELL_EXTERNAL_FW_ATF_TARBALL = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_ATF_CUSTOM_TARBALL_LOCATION))
MARVELL_EXTERNAL_FW_ATF_SITE = $(subst file://,/,$(dir $(MARVELL_EXTERNAL_FW_ATF_TARBALL)))
MARVELL_EXTERNAL_FW_ATF_SITE_METHOD = file
MARVELL_EXTERNAL_FW_ATF_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_ATF_TARBALL))
MARVELL_EXTERNAL_FW_ATF_VERSION = $(call qstrip,$(BR2_MARVELL_RELEASE_ID))
endif

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_ATF_CUSTOM_GIT),y)
define MARVELL_EXTERNAL_FW_EXTRACT_ATF_CMDS
	git clone $(MARVELL_EXTERNAL_FW_ATF_SITE) -b $(MARVELL_EXTERNAL_FW_ATF_VERSION) $(@D)/firmware/atf
endef
else
define MARVELL_EXTERNAL_FW_EXTRACT_ATF_CMDS
	mkdir $(@D)/firmware/atf
	tar xf $(MARVELL_EXTERNAL_FW_ATF_SITE)$(MARVELL_EXTERNAL_FW_ATF_SOURCE) --strip-components=1 -C $(@D)/firmware/atf
endef
endif

# UBOOT #
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_UBOOT_CUSTOM_GIT),y)
MARVELL_EXTERNAL_FW_UBOOT_SITE = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_UBOOT_CUSTOM_REPO_URL))
MARVELL_EXTERNAL_FW_UBOOT_SITE_METHOD = git
MARVELL_EXTERNAL_FW_UBOOT_VERSION = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_UBOOT_CUSTOM_REPO_VERSION))
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_UBOOT_CUSTOM_TARBALL),y)
MARVELL_EXTERNAL_FW_UBOOT_TARBALL = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_UBOOT_CUSTOM_TARBALL_LOCATION))
MARVELL_EXTERNAL_FW_UBOOT_SITE = $(subst file://,/,$(dir $(MARVELL_EXTERNAL_FW_UBOOT_TARBALL)))
MARVELL_EXTERNAL_FW_UBOOT_SITE_METHOD = file
MARVELL_EXTERNAL_FW_UBOOT_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_UBOOT_TARBALL))
MARVELL_EXTERNAL_FW_UBOOT_VERSION = $(call qstrip,$(BR2_MARVELL_RELEASE_ID))
endif

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_UBOOT_CUSTOM_GIT),y)
define MARVELL_EXTERNAL_FW_EXTRACT_UBOOT_CMDS
	git clone $(MARVELL_EXTERNAL_FW_UBOOT_SITE) -b $(MARVELL_EXTERNAL_FW_UBOOT_VERSION) $(@D)/bootloader/u-boot
endef
else
define MARVELL_EXTERNAL_FW_EXTRACT_UBOOT_CMDS
	mkdir $(@D)/bootloader/u-boot
	tar xf $(MARVELL_EXTERNAL_FW_UBOOT_SITE)$(MARVELL_EXTERNAL_FW_UBOOT_SOURCE) --strip-components=1 -C $(@D)/bootloader/u-boot
endef
endif

## ECP ##
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_ECP_CUSTOM_GIT),y)
MARVELL_EXTERNAL_FW_ECP_SITE = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_ECP_CUSTOM_REPO_URL))
MARVELL_EXTERNAL_FW_ECP_SITE_METHOD = git
MARVELL_EXTERNAL_FW_ECP_VERSION = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_ECP_CUSTOM_REPO_VERSION))
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_ECP_CUSTOM_TARBALL),y)
MARVELL_EXTERNAL_FW_ECP_TARBALL = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_ECP_CUSTOM_TARBALL_LOCATION))
MARVELL_EXTERNAL_FW_ECP_SITE = $(subst file://,/,$(dir $(MARVELL_EXTERNAL_FW_ECP_TARBALL)))
MARVELL_EXTERNAL_FW_ECP_SITE_METHOD = file
MARVELL_EXTERNAL_FW_ECP_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_ECP_TARBALL))
MARVELL_EXTERNAL_FW_ECP_VERSION = $(call qstrip,$(BR2_MARVELL_RELEASE_ID))
endif

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_ECP_CUSTOM_GIT),y)
define MARVELL_EXTERNAL_FW_EXTRACT_ECP_CMDS
        git clone $(MARVELL_EXTERNAL_FW_ECP_SITE) -b $(MARVELL_EXTERNAL_FW_ECP_VERSION) $(@D)/firmware/$(MARVELL_EXTERNAL_FW_ECP_LOC)
endef
else
define MARVELL_EXTERNAL_FW_EXTRACT_ECP_CMDS
        mkdir -p $(@D)/firmware/$(MARVELL_EXTERNAL_FW_ECP_LOC)/
        tar xf $(MARVELL_EXTERNAL_FW_ECP_SITE)$(MARVELL_EXTERNAL_FW_ECP_SOURCE) --strip-components=1 -C $(@D)/firmware/$(MARVELL_EXTERNAL_FW_ECP_LOC)
endef
endif

## ECP_HAL ###

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_ECP_HAL),y)

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_ECP_HAL_CUSTOM_GIT),y)
MARVELL_EXTERNAL_FW_ECP_HAL_SITE = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_ECP_HAL_CUSTOM_REPO_URL))
MARVELL_EXTERNAL_FW_ECP_HAL_SITE_METHOD = git
MARVELL_EXTERNAL_FW_ECP_HAL_VERSION = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_ECP_HAL_CUSTOM_REPO_VERSION))
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_ECP_HAL_CUSTOM_TARBALL),y)
MARVELL_EXTERNAL_FW_ECP_HAL_TARBALL = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_ECP_HAL_CUSTOM_TARBALL_LOCATION))
MARVELL_EXTERNAL_FW_ECP_HAL_SITE = $(subst file://,/,$(dir $(MARVELL_EXTERNAL_FW_ECP_HAL_TARBALL)))
MARVELL_EXTERNAL_FW_ECP_HAL_SITE_METHOD = file
MARVELL_EXTERNAL_FW_ECP_HAL_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_ECP_HAL_TARBALL))
MARVELL_EXTERNAL_FW_ECP_HAL_VERSION = $(call qstrip,$(BR2_MARVELL_RELEASE_ID))
endif

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_ECP_HAL_CUSTOM_GIT),y)
define MARVELL_EXTERNAL_FW_EXTRACT_ECP_HAL_CMDS
        git clone $(MARVELL_EXTERNAL_FW_ECP_HAL_SITE) -b $(MARVELL_EXTERNAL_FW_ECP_HAL_VERSION) $(@D)/firmware/xcp/modules/hal/cn20k
endef
else
define MARVELL_EXTERNAL_FW_EXTRACT_ECP_HAL_CMDS
        mkdir -p $(@D)/firmware/xcp/modules/hal/cn20k 
        tar xf $(MARVELL_EXTERNAL_FW_ECP_HAL_SITE)$(MARVELL_EXTERNAL_FW_ECP_HAL_SOURCE) --strip-components=1 -C $(@D)/firmware/xcp/modules/hal/cn20k
endef
endif


endif

##Zephyr Project##
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_ZEPHYR_PROJECT),y)
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_ZEPHYR_PROJECT_CUSTOM_GIT),y)
MARVELL_EXTERNAL_FW_ZEPHYR_PROJECT_SITE = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_ZEPHYR_PROJECT_CUSTOM_REPO_URL))
MARVELL_EXTERNAL_FW_ZEPHYR_PROJECT_SITE_METHOD = git
MARVELL_EXTERNAL_FW_ZEPHYR_PROJECT_VERSION = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_ZEPHYR_PROJECT_CUSTOM_REPO_VERSION))
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_ZEPHYR_PROJECT_CUSTOM_TARBALL),y)
MARVELL_EXTERNAL_FW_ZEPHYR_PROJECT_TARBALL = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_ZEPHYR_PROJECT_CUSTOM_TARBALL_LOCATION))
MARVELL_EXTERNAL_FW_ZEPHYR_PROJECT_SITE = $(subst file://,/,$(dir $(MARVELL_EXTERNAL_FW_ZEPHYR_PROJECT_TARBALL)))
MARVELL_EXTERNAL_FW_ZEPHYR_PROJECT_SITE_METHOD = file
MARVELL_EXTERNAL_FW_ZEPHYR_PROJECT_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_ZEPHYR_PROJECT_TARBALL))
MARVELL_EXTERNAL_FW_ZEPHYR_PROJECT_VERSION = $(call qstrip,$(BR2_MARVELL_RELEASE_ID))
endif

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_ZEPHYR_PROJECT_CUSTOM_GIT),y)
define MARVELL_EXTERNAL_FW_EXTRACT_ZEPHYR_PROJECT_CMDS
        git clone $(MARVELL_EXTERNAL_FW_ZEPHYR_PROJECT_SITE) -b $(MARVELL_EXTERNAL_FW_ZEPHYR_PROJECT_VERSION) $(@D)/firmware/xcp/zephyrproject/zephyr
endef
else
define MARVELL_EXTERNAL_FW_EXTRACT_ZEPHYR_PROJECT_CMDS
        mkdir -p $(@D)/firmware/xcp/zephyrproject/zephyr
        tar xf $(MARVELL_EXTERNAL_FW_ZEPHYR_PROJECT_SITE)$(MARVELL_EXTERNAL_FW_ZEPHYR_PROJECT_SOURCE) --strip-components=1 -C $(@D)/firmware/xcp/zephyrproject/zephyr
endef
endif
endif

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_CMSIS),y)
#CMSIS#
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_CMSIS_CUSTOM_GIT),y)
MARVELL_EXTERNAL_FW_CMSIS_SITE = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_CMSIS_CUSTOM_REPO_URL))
MARVELL_EXTERNAL_FW_CMSIS_SITE_METHOD = git
MARVELL_EXTERNAL_FW_CMSIS_VERSION = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_CMSIS_CUSTOM_REPO_VERSION))
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_CMSIS_CUSTOM_TARBALL),y)
MARVELL_EXTERNAL_FW_CMSIS_TARBALL = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_CMSIS_CUSTOM_TARBALL_LOCATION))
MARVELL_EXTERNAL_FW_CMSIS_SITE = $(subst file://,/,$(dir $(MARVELL_EXTERNAL_FW_CMSIS_TARBALL)))
MARVELL_EXTERNAL_FW_CMSIS_SITE_METHOD = file
MARVELL_EXTERNAL_FW_CMSIS_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_CMSIS_TARBALL))
MARVELL_EXTERNAL_FW_CMSIS_VERSION = $(call qstrip,$(BR2_MARVELL_RELEASE_ID))
endif

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_CMSIS_CUSTOM_GIT),y)
define MARVELL_EXTERNAL_FW_EXTRACT_CMSIS_CMDS
        git clone $(MARVELL_EXTERNAL_FW_CMSIS_SITE) -b $(MARVELL_EXTERNAL_FW_CMSIS_VERSION) $(@D)/firmware/xcp/zephyrproject/modules/hal/cmsis
endef
else
define MARVELL_EXTERNAL_FW_EXTRACT_CMSIS_CMDS
        mkdir -p $(@D)/firmware/xcp/zephyrproject/modules/hal/cmsis
        tar xf $(MARVELL_EXTERNAL_FW_CMSIS_SITE)$(MARVELL_EXTERNAL_FW_CMSIS_SOURCE) --strip-components=1 -C $(@D)/firmware/xcp/zephyrproject/modules/hal/cmsis
endef
endif
endif

## PCP ##
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_PCP_HAL),y)

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_PCP_CUSTOM_GIT),y)
MARVELL_EXTERNAL_FW_PCP_SITE = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_PCP_CUSTOM_REPO_URL))
MARVELL_EXTERNAL_FW_PCP_SITE_METHOD = git
MARVELL_EXTERNAL_FW_PCP_VERSION = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_PCP_CUSTOM_REPO_VERSION))
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_PCP_CUSTOM_TARBALL),y)
MARVELL_EXTERNAL_FW_PCP_TARBALL = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_PCP_CUSTOM_TARBALL_LOCATION))
MARVELL_EXTERNAL_FW_PCP_SITE = $(subst file://,/,$(dir $(MARVELL_EXTERNAL_FW_PCP_TARBALL)))
MARVELL_EXTERNAL_FW_PCP_SITE_METHOD = file
MARVELL_EXTERNAL_FW_PCP_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_PCP_TARBALL))
MARVELL_EXTERNAL_FW_PCP_VERSION = $(call qstrip,$(BR2_MARVELL_RELEASE_ID))
endif

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_PCP_CUSTOM_GIT),y)
define MARVELL_EXTERNAL_FW_EXTRACT_PCP_CMDS
        git clone $(MARVELL_EXTERNAL_FW_PCP_SITE) -b $(MARVELL_EXTERNAL_FW_PCP_VERSION) $(@D)/firmware/xcp/pcp
endef
else
define MARVELL_EXTERNAL_FW_EXTRACT_PCP_CMDS
        mkdir -p $(@D)/firmware/xcp/pcp
        tar xf $(MARVELL_EXTERNAL_FW_PCP_SITE)$(MARVELL_EXTERNAL_FW_PCP_SOURCE) --strip-components=1 -C $(@D)/firmware/xcp/pcp
endef
endif

## PCP_HAL ###

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_PCP_HAL_CUSTOM_GIT),y)
MARVELL_EXTERNAL_FW_PCP_HAL_SITE = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_PCP_HAL_CUSTOM_REPO_URL))
MARVELL_EXTERNAL_FW_PCP_HAL_SITE_METHOD = git
MARVELL_EXTERNAL_FW_PCP_HAL_VERSION = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_PCP_HAL_CUSTOM_REPO_VERSION))
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_PCP_HAL_CUSTOM_TARBALL),y)
MARVELL_EXTERNAL_FW_PCP_HAL_TARBALL = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_PCP_HAL_CUSTOM_TARBALL_LOCATION))
MARVELL_EXTERNAL_FW_PCP_HAL_SITE = $(subst file://,/,$(dir $(MARVELL_EXTERNAL_FW_PCP_HAL_TARBALL)))
MARVELL_EXTERNAL_FW_PCP_HAL_SITE_METHOD = file
MARVELL_EXTERNAL_FW_PCP_HAL_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_PCP_HAL_TARBALL))
MARVELL_EXTERNAL_FW_PCP_HAL_VERSION = $(call qstrip,$(BR2_MARVELL_RELEASE_ID))
endif

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_PCP_HAL_CUSTOM_GIT),y)
define MARVELL_EXTERNAL_FW_EXTRACT_PCP_HAL_CMDS
        git clone $(MARVELL_EXTERNAL_FW_PCP_HAL_SITE) -b $(MARVELL_EXTERNAL_FW_PCP_HAL_VERSION) $(@D)/firmware/xcp/pcp/modules/hal/pcp
endef
else
define MARVELL_EXTERNAL_FW_EXTRACT_PCP_HAL_CMDS
        mkdir -p $(@D)/firmware/xcp/pcp/modules/hal/pcp
        tar xf $(MARVELL_EXTERNAL_FW_PCP_HAL_SITE)$(MARVELL_EXTERNAL_FW_PCP_HAL_SOURCE) --strip-components=1 -C $(@D)/firmware/xcp/pcp/modules/hal/pcp
endef
endif


endif


## MCP ##
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_MCP_CUSTOM_GIT),y)
MARVELL_EXTERNAL_FW_MCP_SITE = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_MCP_CUSTOM_REPO_URL))
MARVELL_EXTERNAL_FW_MCP_SITE_METHOD = git
MARVELL_EXTERNAL_FW_MCP_VERSION = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_MCP_CUSTOM_REPO_VERSION))
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_MCP_CUSTOM_TARBALL),y)
MARVELL_EXTERNAL_FW_MCP_TARBALL = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_MCP_CUSTOM_TARBALL_LOCATION))
MARVELL_EXTERNAL_FW_MCP_SITE = $(subst file://,/,$(dir $(MARVELL_EXTERNAL_FW_MCP_TARBALL)))
MARVELL_EXTERNAL_FW_MCP_SITE_METHOD = file
MARVELL_EXTERNAL_FW_MCP_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_MCP_TARBALL))
MARVELL_EXTERNAL_FW_MCP_VERSION = $(call qstrip,$(BR2_MARVELL_RELEASE_ID))
endif

ifeq ($(BR2_MARVELL_EXTERNAL_FW_MCP_BUILD),y)
ifeq ($(BR2_MARVELL_SOC_FAMILY),"CN10K")
# Set MIPS toolchain path and URLs
MIPS_PATH = $(HOME)/codescape
MIPS_URL = "https://artifactory.marvell.com/artifactory/sources.buildroot-virtual/Codescape.GNU.Tools.Package.2017.10-08.for.MIPS.MTI.Bare.Metal.CentOS-5.x86_64.tar.gz"
MIPS_TAR = ${MIPS_PATH}/mips_toolchain.tar.gz

define MARVELL_EXTERNAL_FW_MIPS_MCP
		echo "Create directory for MIPS toolchain if not exists"
		mkdir -p ${MIPS_PATH}
		# Check if the toolchain file already exists
		if [ -f ${MIPS_TAR} ]; then \
			echo "MIPS toolchain file already exists at ${MIPS_TAR}. Skipping download."; \
		else \
			echo "Downloading MIPS toolchain..."; \
			wget -O ${MIPS_TAR} ${MIPS_URL}; \
		fi
		# Extract toolchain
		if [ -f ${MIPS_TAR} ]; then \
			echo "Extracting MIPS toolchain..."; \
			tar -xzf ${MIPS_TAR} -C ${MIPS_PATH}; \
		else \
			echo "Error: MIPS toolchain archive not found!"; \
			exit 1; \
		fi
endef
endif
endif

ifeq ($(BR2_MARVELL_SOC_FAMILY), "CN20K")
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_MCP_CUSTOM_GIT),y)
define MARVELL_EXTERNAL_FW_EXTRACT_MCP_CMDS
        git clone $(MARVELL_EXTERNAL_FW_MCP_SITE) -b $(MARVELL_EXTERNAL_FW_MCP_VERSION) $(@D)/firmware/xcp/mcp/mcp_app
endef
else
define MARVELL_EXTERNAL_FW_EXTRACT_MCP_CMDS
        mkdir -p $(@D)/firmware/xcp/mcp/mcp_app
        tar xf $(MARVELL_EXTERNAL_FW_MCP_SITE)$(MARVELL_EXTERNAL_FW_MCP_SOURCE) --strip-components=1 -C $(@D)/firmware/xcp/mcp/mcp_app
endef
endif
else
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_MCP_CUSTOM_GIT),y)
define MARVELL_EXTERNAL_FW_EXTRACT_MCP_CMDS
		$(MARVELL_EXTERNAL_FW_MIPS_MCP)
        git clone $(MARVELL_EXTERNAL_FW_MCP_SITE) -b $(MARVELL_EXTERNAL_FW_MCP_VERSION) $(@D)/firmware/mcp
endef
else
define MARVELL_EXTERNAL_FW_EXTRACT_MCP_CMDS
		$(MARVELL_EXTERNAL_FW_MIPS_MCP)
        mkdir $(@D)/firmware/mcp
        tar xf $(MARVELL_EXTERNAL_FW_MCP_SITE)$(MARVELL_EXTERNAL_FW_MCP_SOURCE) --strip-components=1 -C $(@D)/firmware/mcp
endef
endif
endif

## CS_SDK ###
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_CS_SDK),y)
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_CS_SDK_CUSTOM_GIT),y)
MARVELL_EXTERNAL_FW_CS_SDK_SITE = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_CS_SDK_CUSTOM_REPO_URL))
MARVELL_EXTERNAL_FW_CS_SDK_SITE_METHOD = git
MARVELL_EXTERNAL_FW_CS_SDK_VERSION = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_CS_SDK_CUSTOM_REPO_VERSION))
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_CS_SDK_CUSTOM_TARBALL),y)
MARVELL_EXTERNAL_FW_CS_SDK_TARBALL = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_CS_SDK_CUSTOM_TARBALL_LOCATION))
MARVELL_EXTERNAL_FW_CS_SDK_SITE = $(subst file://,/,$(dir $(MARVELL_EXTERNAL_FW_CS_SDK_TARBALL)))
MARVELL_EXTERNAL_FW_CS_SDK_SITE_METHOD = file
MARVELL_EXTERNAL_FW_CS_SDK_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_CS_SDK_TARBALL))
MARVELL_EXTERNAL_FW_CS_SDK_VERSION = $(call qstrip,$(BR2_MARVELL_RELEASE_ID))
endif

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_CS_SDK_CUSTOM_GIT),y)
define MARVELL_EXTERNAL_FW_EXTRACT_CS_SDK_CMDS
        git clone $(MARVELL_EXTERNAL_FW_CS_SDK_SITE) -b $(MARVELL_EXTERNAL_FW_CS_SDK_VERSION) $(@D)/firmware/chip-security-sdk
endef
else
define MARVELL_EXTERNAL_FW_EXTRACT_CS_SDK_CMDS
        mkdir -p $(@D)/firmware/chip-security-sdk
        tar xf $(MARVELL_EXTERNAL_FW_CS_SDK_SITE)$(MARVELL_EXTERNAL_FW_CS_SDK_SOURCE) --strip-components=1 -C $(@D)/firmware/chip-security-sdk
endef
endif
endif

## PEMEP ###
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_PEMEP),y)
CROSS_COMPILE_M7 = $(@D)/tools-armv7/bin/arm-none-eabi-
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_PEMEP_CUSTOM_GIT),y)
MARVELL_EXTERNAL_FW_PEMEP_SITE = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_PEMEP_CUSTOM_REPO_URL))
MARVELL_EXTERNAL_FW_PEMEP_SITE_METHOD = git
MARVELL_EXTERNAL_FW_PEMEP_VERSION = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_PEMEP_CUSTOM_REPO_VERSION))
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_PEMEP_CUSTOM_TARBALL),y)
MARVELL_EXTERNAL_FW_PEMEP_TARBALL = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_PEMEP_CUSTOM_TARBALL_LOCATION))
MARVELL_EXTERNAL_FW_PEMEP_SITE = $(subst file://,/,$(dir $(MARVELL_EXTERNAL_FW_PEMEP_TARBALL)))
MARVELL_EXTERNAL_FW_PEMEP_SITE_METHOD = file
MARVELL_EXTERNAL_FW_PEMEP_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_PEMEP_TARBALL))
MARVELL_EXTERNAL_FW_PEMEP_VERSION = $(call qstrip,$(BR2_MARVELL_RELEASE_ID))
endif

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_PEMEP_CUSTOM_GIT),y)
define MARVELL_EXTERNAL_FW_EXTRACT_PEMEP_CMDS
        git clone $(MARVELL_EXTERNAL_FW_PEMEP_SITE) -b $(MARVELL_EXTERNAL_FW_PEMEP_VERSION) $(@D)/firmware/pemep
endef
else
define MARVELL_EXTERNAL_FW_EXTRACT_PEMEP_CMDS
        mkdir -p $(@D)/firmware/pemep
        tar xf $(MARVELL_EXTERNAL_FW_PEMEP_SITE)$(MARVELL_EXTERNAL_FW_PEMEP_SOURCE) --strip-components=1 -C $(@D)/firmware/pemep
endef
endif
ifneq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_PEMEP_CONFIG_FILE),"")
MARVELL_EXTERNAL_FW_MAKE_OPTS += PEM_EP_CONFIG_FILE=$(patsubst "%",%,$(BR2_TARGET_MARVELL_EXTERNAL_FW_PEMEP_CONFIG_FILE))
endif
endif

##LIBMCTP##

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_LIBMCTP),y)
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_LIBMCTP_CUSTOM_GIT),y)
MARVELL_EXTERNAL_FW_LIBMCTP_SITE = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_LIBMCTP_CUSTOM_REPO_URL))
MARVELL_EXTERNAL_FW_LIBMCTP_SITE_METHOD = git
MARVELL_EXTERNAL_FW_LIBMCTP_VERSION = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_LIBMCTP_CUSTOM_REPO_VERSION))
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_LIBMCTP_CUSTOM_TARBALL),y)
MARVELL_EXTERNAL_FW_LIBMCTP_TARBALL = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_LIBMCTP_CUSTOM_TARBALL_LOCATION))
MARVELL_EXTERNAL_FW_LIBMCTP_SITE = $(subst file://,/,$(dir $(MARVELL_EXTERNAL_FW_LIBMCTP_TARBALL)))
MARVELL_EXTERNAL_FW_LIBMCTP_SITE_METHOD = file
MARVELL_EXTERNAL_FW_LIBMCTP_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_LIBMCTP_TARBALL))
MARVELL_EXTERNAL_FW_LIBMCTP_VERSION = $(call qstrip,$(BR2_MARVELL_RELEASE_ID))
endif

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_LIBMCTP_CUSTOM_GIT),y)
define MARVELL_EXTERNAL_FW_EXTRACT_LIBMCTP_CMDS
	git clone $(MARVELL_EXTERNAL_FW_LIBMCTP_SITE) -b $(MARVELL_EXTERNAL_FW_LIBMCTP_VERSION) $(@D)/firmware/xcp/modules/lib/libmctp
endef
else
define MARVELL_EXTERNAL_FW_EXTRACT_LIBMCTP_CMDS
	mkdir -p $(@D)/firmware/xcp/modules/lib/libmctp
	tar xf $(MARVELL_EXTERNAL_FW_LIBMCTP_SITE)$(MARVELL_EXTERNAL_FW_LIBMCTP_SOURCE) --strip-components=1 -C $(@D)/firmware/xcp/modules/lib/libmctp
endef
endif
endif

##LIBPLDM##

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_LIBPLDM),y)
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_LIBPLDM_CUSTOM_GIT),y)
MARVELL_EXTERNAL_FW_LIBPLDM_SITE = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_LIBPLDM_CUSTOM_REPO_URL))
MARVELL_EXTERNAL_FW_LIBPLDM_SITE_METHOD = git
MARVELL_EXTERNAL_FW_LIBPLDM_VERSION = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_LIBPLDM_CUSTOM_REPO_VERSION))
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_LIBPLDM_CUSTOM_TARBALL),y)
MARVELL_EXTERNAL_FW_LIBPLDM_TARBALL = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_LIBPLDM_CUSTOM_TARBALL_LOCATION))
MARVELL_EXTERNAL_FW_LIBPLDM_SITE = $(subst file://,/,$(dir $(MARVELL_EXTERNAL_FW_LIBPLDM_TARBALL)))
MARVELL_EXTERNAL_FW_LIBPLDM_SITE_METHOD = file
MARVELL_EXTERNAL_FW_LIBPLDM_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_LIBPLDM_TARBALL))
MARVELL_EXTERNAL_FW_LIBPLDM_VERSION = $(call qstrip,$(BR2_MARVELL_RELEASE_ID))
endif

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_LIBPLDM_CUSTOM_GIT),y)
define MARVELL_EXTERNAL_FW_EXTRACT_LIBPLDM_CMDS
	git clone $(MARVELL_EXTERNAL_FW_LIBPLDM_SITE) -b $(MARVELL_EXTERNAL_FW_LIBPLDM_VERSION) $(@D)/firmware/xcp/modules/lib/libpldm
endef
else
define MARVELL_EXTERNAL_FW_EXTRACT_LIBPLDM_CMDS
	mkdir -p $(@D)/firmware/xcp/modules/lib/libpldm
	tar xf $(MARVELL_EXTERNAL_FW_LIBPLDM_SITE)$(MARVELL_EXTERNAL_FW_LIBPLDM_SOURCE) --strip-components=1 -C $(@D)/firmware/xcp/modules/lib/libpldm
endef
endif
endif

##MCTPD##

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_MCTPD),y)
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_MCTPD_CUSTOM_GIT),y)
MARVELL_EXTERNAL_FW_MCTPD_SITE = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_MCTPD_CUSTOM_REPO_URL))
MARVELL_EXTERNAL_FW_MCTPD_SITE_METHOD = git
MARVELL_EXTERNAL_FW_MCTPD_VERSION = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_MCTPD_CUSTOM_REPO_VERSION))
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_MCTPD_CUSTOM_TARBALL),y)
MARVELL_EXTERNAL_FW_MCTPD_TARBALL = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_MCTPD_CUSTOM_TARBALL_LOCATION))
MARVELL_EXTERNAL_FW_MCTPD_SITE = $(subst file://,/,$(dir $(MARVELL_EXTERNAL_FW_MCTPD_TARBALL)))
MARVELL_EXTERNAL_FW_MCTPD_SITE_METHOD = file
MARVELL_EXTERNAL_FW_MCTPD_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_MCTPD_TARBALL))
MARVELL_EXTERNAL_FW_MCTPD_VERSION = $(call qstrip,$(BR2_MARVELL_RELEASE_ID))
endif

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_MCTPD_CUSTOM_GIT),y)
define MARVELL_EXTERNAL_FW_EXTRACT_MCTPD_CMDS
	git clone $(MARVELL_EXTERNAL_FW_MCTPD_SITE) -b $(MARVELL_EXTERNAL_FW_MCTPD_VERSION) $(@D)/firmware/xcp/mcp/mcp_app/pmci/mctp
endef
else
define MARVELL_EXTERNAL_FW_EXTRACT_MCTPD_CMDS
	mkdir -p $(@D)//firmware/xcp/mcp/mcp_app/pmci/mctp
	tar xf $(MARVELL_EXTERNAL_FW_MCTPD_SITE)$(MARVELL_EXTERNAL_FW_MCTPD_SOURCE) --strip-components=1 -C $(@D)/firmware/xcp/mcp/mcp_app/pmci/mctp
endef
endif
endif


##PLDM##
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_PLDMD),y)
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_PLDMD_CUSTOM_GIT),y)
MARVELL_EXTERNAL_FW_PLDMD_SITE = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_PLDMD_CUSTOM_REPO_URL))
MARVELL_EXTERNAL_FW_PLDMD_SITE_METHOD = git
MARVELL_EXTERNAL_FW_PLDMD_VERSION = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_PLDMD_CUSTOM_REPO_VERSION))
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_PLDMD_CUSTOM_TARBALL),y)
MARVELL_EXTERNAL_FW_PLDMD_TARBALL = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_PLDMD_CUSTOM_TARBALL_LOCATION))
MARVELL_EXTERNAL_FW_PLDMD_SITE = $(subst file://,/,$(dir $(MARVELL_EXTERNAL_FW_PLDMD_TARBALL)))
MARVELL_EXTERNAL_FW_PLDMD_SITE_METHOD = file
MARVELL_EXTERNAL_FW_PLDMD_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_PLDMD_TARBALL))
MARVELL_EXTERNAL_FW_PLDMD_VERSION = $(call qstrip,$(BR2_MARVELL_RELEASE_ID))
endif

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_PLDMD_CUSTOM_GIT),y)
define MARVELL_EXTERNAL_FW_EXTRACT_PLDMD_CMDS
	git clone $(MARVELL_EXTERNAL_FW_PLDMD_SITE) -b $(MARVELL_EXTERNAL_FW_PLDMD_VERSION) $(@D)/firmware/xcp/mcp/mcp_app/pmci/pldm
endef
else
define MARVELL_EXTERNAL_FW_EXTRACT_PLDMD_CMDS
	mkdir -p $(@D)/firmware/xcp/mcp/mcp_app/pmci/pldm
	tar xf $(MARVELL_EXTERNAL_FW_PLDMD_SITE)$(MARVELL_EXTERNAL_FW_PLDMD_SOURCE) --strip-components=1 -C $(@D)/firmware/xcp/mcp/mcp_app/pmci/pldm
endef
endif
endif

# EBF #
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_EBF_CUSTOM_GIT),y)
MARVELL_EXTERNAL_FW_EBF_SITE = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_EBF_CUSTOM_REPO_URL))
MARVELL_EXTERNAL_FW_EBF_SITE_METHOD = git
MARVELL_EXTERNAL_FW_EBF_VERSION = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_EBF_CUSTOM_REPO_VERSION))
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_EBF_CUSTOM_TARBALL),y)
MARVELL_EXTERNAL_FW_EBF_TARBALL = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_EBF_CUSTOM_TARBALL_LOCATION))
MARVELL_EXTERNAL_FW_EBF_SITE = $(subst file://,/,$(dir $(MARVELL_EXTERNAL_FW_EBF_TARBALL)))
MARVELL_EXTERNAL_FW_EBF_SITE_METHOD = file
MARVELL_EXTERNAL_FW_EBF_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_EBF_TARBALL))
MARVELL_EXTERNAL_FW_EBF_VERSION = $(call qstrip,$(BR2_MARVELL_RELEASE_ID))
endif

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_EBF_CUSTOM_GIT),y)
define MARVELL_EXTERNAL_FW_EXTRACT_EBF_CMDS
	git clone $(MARVELL_EXTERNAL_FW_EBF_SITE) -b $(MARVELL_EXTERNAL_FW_EBF_VERSION) $(@D)/firmware/ebf
endef
else
define MARVELL_EXTERNAL_FW_EXTRACT_EBF_CMDS
	mkdir $(@D)/firmware/ebf
	tar xf $(MARVELL_EXTERNAL_FW_EBF_SITE)$(MARVELL_EXTERNAL_FW_EBF_SOURCE) --strip-components=1 -C $(@D)/firmware/ebf
endef
endif

# UEFI #
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_UEFI),y)
MARVELL_EXTERNAL_FW_DEPENDENCIES += host-acpica
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_UEFI_CUSTOM_GIT),y)
MARVELL_EXTERNAL_FW_UEFI_SITE = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_UEFI_CUSTOM_REPO_URL))
MARVELL_EXTERNAL_FW_UEFI_SITE_METHOD = git
MARVELL_EXTERNAL_FW_UEFI_VERSION = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_UEFI_CUSTOM_REPO_VERSION))
export VERSION=devel
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_UEFI_CUSTOM_TARBALL),y)
MARVELL_EXTERNAL_FW_UEFI_TARBALL = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_UEFI_CUSTOM_TARBALL_LOCATION))
MARVELL_EXTERNAL_FW_UEFI_SITE = $(subst file://,/,$(dir $(MARVELL_EXTERNAL_FW_UEFI_TARBALL)))
MARVELL_EXTERNAL_FW_UEFI_SITE_METHOD = file
MARVELL_EXTERNAL_FW_UEFI_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_UEFI_TARBALL))
MARVELL_EXTERNAL_FW_UEFI_VERSION = $(call qstrip,$(BR2_MARVELL_RELEASE_ID))
export VERSION=$(BR2_MARVELL_RELEASE_ID)
endif

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_UEFI_CUSTOM_GIT),y)
define MARVELL_EXTERNAL_FW_EXTRACT_UEFI_CMDS
        git clone $(MARVELL_EXTERNAL_FW_UEFI_SITE) -b $(MARVELL_EXTERNAL_FW_UEFI_VERSION) $(@D)/bootloader/uefi
	cd $(@D)/bootloader/uefi && git submodule update --init
endef
else
define MARVELL_EXTERNAL_FW_EXTRACT_UEFI_CMDS
        mkdir $(@D)/bootloader/uefi
        tar xf $(MARVELL_EXTERNAL_FW_UEFI_SITE)$(MARVELL_EXTERNAL_FW_UEFI_SOURCE) --strip-components=1 -C $(@D)/bootloader/uefi
endef
endif
endif #If uefi enabled

# libtim #
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_LIBTIM_CUSTOM_GIT),y)
MARVELL_EXTERNAL_FW_LIBTIM_SITE = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_LIBTIM_CUSTOM_REPO_URL))
MARVELL_EXTERNAL_FW_LIBTIM_SITE_METHOD = git
MARVELL_EXTERNAL_FW_LIBTIM_VERSION = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_LIBTIM_CUSTOM_REPO_VERSION))
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_LIBTIM_CUSTOM_TARBALL),y)
MARVELL_EXTERNAL_FW_LIBTIM_TARBALL = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_LIBTIM_CUSTOM_TARBALL_LOCATION))
MARVELL_EXTERNAL_FW_LIBTIM_SITE = $(subst file://,/,$(dir $(MARVELL_EXTERNAL_FW_LIBTIM_TARBALL)))
MARVELL_EXTERNAL_FW_LIBTIM_SITE_METHOD = file
MARVELL_EXTERNAL_FW_LIBTIM_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_LIBTIM_TARBALL))
MARVELL_EXTERNAL_FW_LIBTIM_VERSION = $(call qstrip,$(BR2_MARVELL_RELEASE_ID))
endif

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_LIBTIM_CUSTOM_GIT),y)
define MARVELL_EXTERNAL_FW_EXTRACT_LIBTIM_CMDS
        git clone $(MARVELL_EXTERNAL_FW_LIBTIM_SITE) -b $(MARVELL_EXTERNAL_FW_LIBTIM_VERSION) $(@D)/firmware/libtim
	cd $(@D)/firmware/libtim && git submodule update --init
endef
else
define MARVELL_EXTERNAL_FW_EXTRACT_LIBTIM_CMDS
        mkdir $(@D)/firmware/libtim
        tar xf $(MARVELL_EXTERNAL_FW_LIBTIM_SITE)$(MARVELL_EXTERNAL_FW_LIBTIM_SOURCE) --strip-components=1 -C $(@D)/firmware/libtim
endef
endif

# secure boot:sign trusted#
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_SIGNED_TRUSTED),y)
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_MBEDTLS_CUSTOM_GIT),y)
MARVELL_EXTERNAL_FW_MBEDTLS_SITE = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_MBEDTLS_CUSTOM_REPO_URL))
MARVELL_EXTERNAL_FW_MBEDTLS_SITE_METHOD = git
MARVELL_EXTERNAL_FW_MBEDTLS_VERSION = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_MBEDTLS_CUSTOM_REPO_VERSION))
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_MBEDTLS_CUSTOM_TARBALL),y)
MARVELL_EXTERNAL_FW_MBEDTLS_TARBALL = $(call qstrip,$(BR2_TARGET_MARVELL_EXTERNAL_FW_MBEDTLS_CUSTOM_TARBALL_LOCATION))
MARVELL_EXTERNAL_FW_MBEDTLS_SITE = $(subst file://,/,$(dir $(MARVELL_EXTERNAL_FW_MBEDTLS_TARBALL)))
MARVELL_EXTERNAL_FW_MBEDTLS_SITE_METHOD = file
MARVELL_EXTERNAL_FW_MBEDTLS_SOURCE = $(notdir $(MARVELL_EXTERNAL_FW_MBEDTLS_TARBALL))
MARVELL_EXTERNAL_FW_MBEDTLS_VERSION = $(call qstrip,$(BR2_MARVELL_RELEASE_ID))
endif

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_MBEDTLS_CUSTOM_GIT),y)
define MARVELL_EXTERNAL_FW_EXTRACT_MBEDTLS_CMDS
        git clone $(MARVELL_EXTERNAL_FW_MBEDTLS_SITE) -b $(MARVELL_EXTERNAL_FW_MBEDTLS_VERSION) $(@D)/firmware/mbedtls
        cd $(@D)/firmware/mbedtls && git submodule update --init
endef
else
define MARVELL_EXTERNAL_FW_EXTRACT_MBEDTLS_CMDS
        mkdir $(@D)/firmware/mbedtls
        tar xf $(MARVELL_EXTERNAL_FW_MBEDTLS_SITE)$(MARVELL_EXTERNAL_FW_MBEDTLS_SOURCE) --strip-components=1 -C $(@D)/firmware/mbedtls
endef
endif
endif #If Signed-trusted enabled

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_EBF_CUSTOM_TARBALL),y)
define MARVELL_EXTERNAL_FW_DEFINE_SDK_VERSION
if grep -RiIl "sdk-version" $(@D)/dts > /dev/null ; then cd $(@D)/dts && grep -RiIl 'sdk-version' | xargs sed -i 's/.*sdk-version =.*/\t\tsdk-version = $(BR2_MARVELL_RELEASE_ID) ;/g' ; fi
endef

MARVELL_EXTERNAL_FW_MAKE_OPTS += SDK_VERSION=SDK13

else

MARVELL_EXTERNAL_FW_MAKE_OPTS += SDK_VERSION=SDK13-Devel

endif

#ATF_PATCH
define MARVELL_EXTERNAL_FW_ATF_PATCHES
$(foreach atf-patch-dir,$(BR2_GLOBAL_PATCH_DIR), \
	if [[ -d "$(call qstrip,$(atf-patch-dir))/marvell-external-fw/atf/" ]]; then \
	$(APPLY_PATCHES) $(@D)/firmware/atf/ $(call qstrip,$(atf-patch-dir))/marvell-external-fw/atf/ *.patch; \
	fi
)
endef

MARVELL_EXTERNAL_FW_POST_CONFIGURE_HOOKS += MARVELL_EXTERNAL_FW_ATF_PATCHES

#EBF_PATCH
define MARVELL_EXTERNAL_FW_EBF_PATCHES
$(foreach ebf-patch-dir,$(BR2_GLOBAL_PATCH_DIR), \
        if [[ -d "$(call qstrip,$(ebf-patch-dir))/marvell-external-fw/ebf/" ]]; then \
        $(APPLY_PATCHES) $(@D)/firmware/ebf/ $(call qstrip,$(ebf-patch-dir))/marvell-external-fw/ebf/ *.patch; \
        fi
)
endef

MARVELL_EXTERNAL_FW_POST_CONFIGURE_HOOKS += MARVELL_EXTERNAL_FW_EBF_PATCHES

#UBOOT_PATCH
define MARVELL_EXTERNAL_FW_UBOOT_PATCHES
$(foreach uboot-patch-dir,$(BR2_GLOBAL_PATCH_DIR), \
        if [[ -d "$(call qstrip,$(uboot-patch-dir))/marvell-external-fw/uboot/" ]]; then \
        $(APPLY_PATCHES) $(@D)/bootloader/u-boot/ $(call qstrip,$(uboot-patch-dir))/marvell-external-fw/uboot/ *.patch; \
        fi
)
endef

MARVELL_EXTERNAL_FW_POST_CONFIGURE_HOOKS += MARVELL_EXTERNAL_FW_UBOOT_PATCHES


#ACCESS_SECURE_BUILDS
ifeq ($(BR2_MARVELL_DEBUG_ACCESS_SECURE),y)

MARVELL_EXTERNAL_FW_MAKE_OPTS += DBG_ALLOW_SEC_REGN_AC_SMC=1 DBG_ALLOW_SYST_REG_AC=1

define MARVELL_EXTERNAL_FW_ACCESS_SECURE_RENAME
	for file in $(@D)/target/$(MARVELL_EXTERNAL_FW_SOC_TARGET)/images/* ; do mv "$${file}" "$${file%.*}-acc_sec.$${file##*.}"; done
endef

MARVELL_EXTERNAL_FW_PRE_INSTALL_TARGET_HOOKS += MARVELL_EXTERNAL_FW_ACCESS_SECURE_RENAME

endif

ifeq ($(BR2_PACKAGE_PCIE_EP_OCTEONTX), y)
ifeq ($(MARVELL_EXTERNAL_FW_PLATFORM), cnf10kb)
MARVELL_EXTERNAL_FW_MAKE_OPTS += EP_DEFAULT_TIM_SRC_FILE=ep_tims/gen5x4_spread.txt
endif
endif


define MARVELL_EXTERNAL_FW_CONFIGURE_CMDS
	$(MARVELL_EXTERNAL_FW_DEFINE_SDK_VERSION)
	$(MARVELL_EXTERNAL_FW_EXTRACT_TOOLCHAIN_CMDS)
	$(MARVELL_EXTERNAL_FW_EXTRACT_ADDITIONAL_TOOLCHAIN_CMDS)
	$(MARVELL_EXTERNAL_FW_EXTRACT_ATF_CMDS)
	$(MARVELL_EXTERNAL_FW_EXTRACT_EBF_CMDS)
	$(MARVELL_EXTERNAL_FW_EXTRACT_UBOOT_CMDS)
	$(MARVELL_EXTERNAL_FW_EXTRACT_ZEPHYR_PROJECT_CMDS)
	$(MARVELL_EXTERNAL_FW_EXTRACT_CMSIS_CMDS)
	$(MARVELL_EXTERNAL_FW_EXTRACT_PCP_CMDS)
        $(MARVELL_EXTERNAL_FW_EXTRACT_PCP_HAL_CMDS)
	$(MARVELL_EXTERNAL_FW_EXTRACT_ECP_CMDS)
	$(MARVELL_EXTERNAL_FW_EXTRACT_ECP_HAL_CMDS)
	$(MARVELL_EXTERNAL_FW_EXTRACT_MCP_CMDS)
	$(MARVELL_EXTERNAL_FW_EXTRACT_UEFI_CMDS)
	$(MARVELL_EXTERNAL_FW_EXTRACT_CS_SDK_CMDS)
	$(MARVELL_EXTERNAL_FW_EXTRACT_PEMEP_CMDS)
	$(MARVELL_EXTERNAL_FW_EXTRACT_MBEDTLS_CMDS)
	$(MARVELL_EXTERNAL_FW_EXTRACT_LIBTIM_CMDS)
	$(MARVELL_EXTERNAL_FW_EXTRACT_LIBPLDM_CMDS)
	$(MARVELL_EXTERNAL_FW_EXTRACT_LIBMCTP_CMDS)
	$(MARVELL_EXTERNAL_FW_EXTRACT_PLDMD_CMDS)
	$(MARVELL_EXTERNAL_FW_EXTRACT_MCTPD_CMDS)
endef

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_UEFI),y)
ifneq ($(filter $(BR2_MARVELL_SOC_FAMILY),"CN10K" "CN20K"),)
MARVELL_EXTERNAL_FW_IMG_USED = sdk-clean sdk-build BOOTLOADER=uefi
else
MARVELL_EXTERNAL_FW_IMG_USED = uefi-clean uefi-build
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_UEFI_SIGNED_CN10k),y)
MARVELL_EXTERNAL_FW_MAKE_OPTS += TRUST_MODE=secure KEY_YAML_FILE=$(patsubst "%",%,$(BR2_TARGET_MARVELL_EXTERNAL_FW_KEY_YAML_LOC)) \
				 KEY_DIR=$(patsubst "%",%,$(BR2_TARGET_MARVELL_EXTERNAL_FW_KEY_DIR))
endif
else ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_SIGNED_TRUSTED),y)

ifneq ($(filter $(BR2_MARVELL_SOC_FAMILY),"CN10K" "CN20K"),)
MARVELL_EXTERNAL_FW_IMG_USED = sdk-clean sdk-build BOOTLOADER=uboot 
MARVELL_EXTERNAL_FW_MAKE_OPTS += TRUST_MODE=secure KEY_YAML_FILE=$(patsubst "%",%,$(BR2_TARGET_MARVELL_EXTERNAL_FW_KEY_YAML_LOC)) \
				KEY_DIR=$(patsubst "%",%,$(BR2_TARGET_MARVELL_EXTERNAL_FW_KEY_DIR))
ifeq ($(BR2_MARVELL_SOC_FAMILY), "CN20K")
MARVELL_EXTERNAL_FW_MAKE_OPTS += BUILD_SCP=1 NEED_BL32=yes
endif
else 
MARVELL_EXTERNAL_FW_IMG_USED = secure-uboot-clean secure-uboot-build 
#ROT=rot_key.pem 
MARVELL_EXTERNAL_FW_MAKE_OPTS += ROT=$(patsubst "%",%,$(BR2_TARGET_MARVELL_EXTERNAL_FW_SIGNED_TRUSTED_VARS))
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_CREATE_FIT_IMAGE),y)
export FW_CREATE_FIT=$(BR2_TARGET_MARVELL_EXTERNAL_FW_CREATE_FIT_IMAGE)
export FW_FIT_DIR=$(BR2_TARGET_MARVELL_EXTERNAL_FW_FIT_DIR)
MARVELL_EXTERNAL_FW_MAKE_OPTS += FIT_DIR=$(BR2_TARGET_MARVELL_EXTERNAL_FW_FIT_DIR)
endif

else
ifneq ($(filter $(BR2_MARVELL_SOC_FAMILY),"CN10K" "CN20K"),)
MARVELL_EXTERNAL_FW_IMG_USED = sdk-clean sdk-build BOOTLOADER=uboot
else
MARVELL_EXTERNAL_FW_IMG_USED = uboot-clean uboot-build
endif
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_CREATE_FIT_IMAGE),y)
export FW_CREATE_FIT=$(BR2_TARGET_MARVELL_EXTERNAL_FW_CREATE_FIT_IMAGE)
export FW_FIT_DIR=$(BR2_TARGET_MARVELL_EXTERNAL_FW_FIT_DIR)
MARVELL_EXTERNAL_FW_MAKE_OPTS += KEY_DIR=$(BR2_TARGET_MARVELL_EXTERNAL_FW_FIT_DIR)/default/keys
MARVELL_EXTERNAL_FW_MAKE_OPTS += ITS_FILE=$(BR2_TARGET_MARVELL_EXTERNAL_FW_FIT_DIR)/dummy/default.its
MARVELL_EXTERNAL_FW_MAKE_OPTS += FIT_DIR=$(BR2_TARGET_MARVELL_EXTERNAL_FW_FIT_DIR)
MARVELL_EXTERNAL_FW_DEPENDENCIES += host-uboot-tools uboot-tools
endif
endif

#GENERATE ENCRYPTED IMAGE
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_SIGNED_ENCRYPTED),y)
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_HUK),"")
MARVELL_EXTERNAL_FW_MAKE_OPTS += SSK=$(patsubst "%",%,$(BR2_TARGET_MARVELL_EXTERNAL_FW_SSK))
else
MARVELL_EXTERNAL_FW_MAKE_OPTS += HUK=$(patsubst "%",%,$(BR2_TARGET_MARVELL_EXTERNAL_FW_HUK))
endif
MARVELL_EXTERNAL_FW_MAKE_ENCRYPTED = $(MAKE) -C $(@D) secure-rot-key PLAT=$(MARVELL_EXTERNAL_FW_PLATFORM)
endif

ifeq ($(BR2_PACKAGE_OPTEE),y)
MARVELL_EXTERNAL_FW_DEPENDENCIES += optee
MARVELL_EXTERNAL_FW_MAKE_OPTS += \
        NEED_BL32=yes \
        SPD=opteed \
	OPTEE_BUILDROOT=1
MARVELL_EXTERNAL_FW_OPTEE_BIN_HOOK = cp $(@D)/firmware/optee/out/arm-plat-marvell/core/tee.bin $(BINARIES_DIR)/
ifneq ($(filter $(BR2_MARVELL_SOC_FAMILY),"CN10K" "CN20K"),)
MARVELL_EXTERNAL_FW_MAKE_OPTS += INCLUDE_OPTEE=1
endif
ifeq ($(BR2_MARVELL_SOC_FAMILY), "CN20K")
export CSSDK_ROOT=$(@D)/firmware/chip-security-sdk/
endif
define MARVELL_EXTERNAL_FW_OPTEE_LINK_CMDS
	ln -s $(OPTEE_DIR) $(@D)/firmware/optee
endef
endif

#FW_PIE_IMAGE
ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_PIE_IMAGE),y)
MARVELL_EXTERNAL_FW_MAKE_OPTS += PIE_IMAGE=1

ifneq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_SIGNED_TRUSTED),y)
MARVELL_EXTERNAL_FW_MAKE_OPTS += KEY_YAML_FILE=$(patsubst "%",%,$(BR2_TARGET_MARVELL_EXTERNAL_FW_KEY_YAML_LOC))
endif
endif

ifneq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_EBF_EXTRA_DTS_DIR),)
MARVELL_EXTERNAL_FW_MAKE_OPTS += \
	EXTRA_EBF_DTS_DIR=$(BR2_TARGET_MARVELL_EXTERNAL_FW_EBF_EXTRA_DTS_DIR)
endif

ifeq ($(BR2_MARVELL_SOC_FAMILY), "CN10K")
	MARVELL_EXTERNAL_FW_SOC_TARGET=cn10k
	MARVELL_EXTERNAL_FW_SCP_BL0_BIN_HOOK = cp $(@D)/firmware/ebf/cn10k/target-bin/scp_bl0.exe-cn10xx $(BINARIES_DIR)/scp_bl0.exe-${MARVELL_EXTERNAL_FW_PLATFORM}
else ifeq ($(BR2_MARVELL_SOC_FAMILY), "CN20K")
	MARVELL_EXTERNAL_FW_SOC_TARGET=cn20k
endif

define MARVELL_EXTERNAL_FW_COPY_BINARIES
if [ `ls -1 $(@D)/target/$(MARVELL_EXTERNAL_FW_SOC_TARGET)/images/*.bin 2>/dev/null | wc -l ` -gt 0 ]; then \
cp $(@D)/target/$(MARVELL_EXTERNAL_FW_SOC_TARGET)/images/*.bin $(BINARIES_DIR) ; \
fi
endef

ifeq ($(BR2_TARGET_MARVELL_EXTERNAL_FW_UEFI),y)
	MARVELL_EXTERNAL_FW_IMAGE_NAME=flash-uefi-$(MARVELL_EXTERNAL_FW_PLATFORM)
else
	MARVELL_EXTERNAL_FW_IMAGE_NAME=flash-$(MARVELL_EXTERNAL_FW_PLATFORM)
endif
define MARVELL_EXTERNAL_FW_COPY_FWIMG
	cp $(@D)/target/$(MARVELL_EXTERNAL_FW_SOC_TARGET)/images/$(MARVELL_EXTERNAL_FW_IMAGE_NAME).img $(BINARIES_DIR)/marvell-fw.img
endef

define MARVELL_EXTERNAL_FW_BUILD_CMDS
	$(MARVELL_EXTERNAL_FW_OPTEE_LINK_CMDS)
	$(MARVELL_EXTERNAL_FW_MAKE_ENCRYPTED)
	$(TARGET_MAKE_ENV) PATH=$(HOST_DIR)/sbin:$(HOST_DIR)/usr/bin:$(PATH):$(@D)/tools/bin CROSS_COMPILE_M7=$(CROSS_COMPILE_M7) CROSS_COMPILE=$(@D)/tools/bin/aarch64-none-linux-gnu- $(MAKE) -C $(@D) $(MARVELL_EXTERNAL_FW_IMG_USED) PLAT=$(MARVELL_EXTERNAL_FW_PLATFORM) $(MARVELL_EXTERNAL_FW_MAKE_OPTS) $(MARVELL_EXTERNAL_FW_DEFS)
endef

define MARVELL_EXTERNAL_FW_INSTALL_TARGET_CMDS
	cp $(@D)/target/$(MARVELL_EXTERNAL_FW_SOC_TARGET)/images/*.img* $(BINARIES_DIR)
	$(MARVELL_EXTERNAL_FW_SCP_BL0_BIN_HOOK)
	$(MARVELL_EXTERNAL_FW_OPTEE_BIN_HOOK)
endef

MARVELL_EXTERNAL_FW_POST_INSTALL_TARGET_HOOKS += MARVELL_EXTERNAL_FW_COPY_BINARIES
ifneq ($(filter $(BR2_MARVELL_SOC_FAMILY),"CN10K" "CN20K"),)
MARVELL_EXTERNAL_FW_POST_INSTALL_TARGET_HOOKS += MARVELL_EXTERNAL_FW_COPY_FWIMG
endif

$(eval $(generic-package))
